### ISSUE TITLE
data.get_homework() returns invalid attachments

### ISSUE THREAD

**Issue by Rei-666** [kapi2289/vulcan-api#63]
When I'm trying to fetch attachments from homework it returns lists that look like this: 
`[['Name', 'Link'], ['Name', 'Link'], ['Name', 'Link'], ['Name', 'Link'], ['Name', 'Link']]`
Is it possible to get proper links to attachments?
[code](https://github.com/Rei-666/VulcanApi-with-google-spreadsheets/blob/main/VulcanHebe/main.py)

**Comment by Antoni-Czaplicki** [comment]
You can try something like that: 
```
for attachment in homework.attachments:
    print(f"{attachment[0]}: {attachment[1]})
```

**Comment by kuba2k2** [comment]
@Rei-666 you can contribute to this package by implementing e.g. an `Attachment` class that would represent the data object of an attachment.

**Comment by Rei-666** [comment]
Oh sorry, I didn't describe it well. So, I get homework list using `client.data.get_homework()` and then, when I'm trying to get attachments it returns literally 'Name' and 'Link' - hardcoded strings, not actual links to attachments. 

output of the @Antoni-Czaplicki code:
 ![image](https://i.imgur.com/Eui6lub.png)

**Comment by Antoni-Czaplicki** [comment]
Unfortunetly I can't fix that because I don't have any attachments in my homework. As @kuba2k2 said you can contribute to this project. If you want to see unformated response from vulcan add here https://github.com/kapi2289/vulcan-api/blob/master/vulcan/hebe/_api.py#L123 `prnt(envelope)` then you can create attachments class. If you need help write me on discord: antek.#2137
